#Arreglos y clases

##Matrices
Una matriz es un arreglo de N por M elementos
A = \begin{bmatrix}
a_{11} & a_{12} & \dots & a_{1N} \\
a_{21} & a_{22} & \dots & a_{2N} \\
\vdots & \vdots & \ddots & \vdots \\
a_{M1} & a_{M2} & \dots & a_{MN}
\end{bmatrix}


In [7]:
#Vamos a crear una lista de listas
A=[[1,2,3],[4,5,6],[7,8,9]]
print (A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [10]:
# Vamos a crear otra lista
B=[[21,34,40],[71,17,77],[73,81,28]]
print (B)

[[21, 34, 40], [71, 17, 77], [73, 81, 28]]


In [11]:
A+B

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [21, 34, 40], [71, 17, 77], [73, 81, 28]]

In [12]:
2*A

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
A[0][0]
[1,2,3]
#A[0,0] este no se puede poner tiene que usar los 2 corchetes como arriba

[1, 2, 3]

##Vectores y listas

In [20]:
L=A[0]
M=B[0]
print (L)
print (M)
L+M

[1, 2, 3]
[21, 34, 40]


[1, 2, 3, 21, 34, 40]

In [22]:
a=L[0]
b=M[0]
a+b

22

In [23]:
a==1

True

### Suma de "vectores"

In [24]:
len(L)==len(M)


True

In [27]:
suma= [L[0]+M[0],L[1]+M[1],L[2]+M[2]]
suma

[22, 36, 43]

In [28]:
suma=[L[i]+M[i]for i in range(3)]

#### Creacción de funciones globales

La funcion para crear funciones es `def` que se cierra con un debug (print o `return`)

In [31]:
def Hola():
  print("Hola, me llamo Godo")

In [32]:
Hola()

Hola, me llamo Godo


In [36]:
def saludar(s,n):
  print(f"Hola, me llamo {s} y tengo {n} años")#la f sirve para darle el formato de la variable a lo que quieras poner

In [37]:
saludar("Godo", 20)

Hola, me llamo Godo y tengo 20 años


In [41]:
def par(x):
  for x in range(10): #for es para crer un rango
    if x%2==0:
      print(f"{x} es par")
    else: #else es para indicar lo contrareo de lo que queriamos
      print(f"{x}es impar")

In [42]:
par(20)

0 es par
1es impar
2 es par
3es impar
4 es par
5es impar
6 es par
7es impar
8 es par
9es impar


In [43]:
def suma_vectorial(L,M):
  x=[L[i]+M[i] for i in range(len(L))] #
  return x

In [44]:
L=[1,2,3]
M=[21,34,40]

suma_vectorial(L,M)# con esto sumamos los vectores de L y M

[22, 36, 43]

## Modulos o librerias

In [45]:
import math
from math import sqrt, pi

In [46]:
sqrt(68)

8.246211251235321

In [47]:
pi

3.141592653589793

#El modulo Numpy


La funcion array

In [48]:
import numpy as np

L_vector=np.array(L)  #array es para convertir una lista en vector
M_vector=np.array(M)

L_vector+ M_vector

array([22, 36, 43])

In [52]:
C=[9,2,2,2,3,3,2,17,2]
A=[8, 1, 1, 1, 2, 2, 1, 16,1]

C_matriz=np.array(C).reshape(3,3)
A_matriz=np.array(A).reshape(3,3)

print(C_matriz)
print(A_matriz)

[[ 9  2  2]
 [ 2  3  3]
 [ 2 17  2]]
[[ 8  1  1]
 [ 1  2  2]
 [ 1 16  1]]


In [53]:
C_matriz @ A_matriz

array([[76, 45, 15],
       [22, 56, 11],
       [35, 68, 38]])

In [54]:
A_matriz @ C_matriz

array([[76, 36, 21],
       [17, 42, 12],
       [43, 67, 52]])